version: '3.8'

services:
  #backend
  oz-map-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oz-map-backend
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - .:/usr/src/app
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Mongo Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - my_network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  my_network:
    name: global
    driver: bridge
